
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import StoreProvider from "./StoreProvider";
import AuthProvider from "@/context/SessionProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Nextflit clone",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-black" lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <AuthProvider>
          <StoreProvider>
            <Theme>
              {children}
            </Theme>
          </StoreProvider>
        </AuthProvider>
        {/* <>
          <StoreProvider>
            <Theme>
              {children}
            </Theme>
          </StoreProvider>
        </> */}
      </body>
    </html>
  );
}
